### ISSUE TITLE
Allow for internal load balancers for kubernetes

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform-provider-azurerm#18221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order for an AKS Kubernetes cluster to be fully private, it has to have an internal load balancer (see https://docs.microsoft.com/en-us/azure/aks/internal-lb). However, with the current AKS resource in Azurerm, clusters have internet-exposed load balancers created and there doesn't seem to be any way to customize the Kubernetes resource code to change this.

There should be an argument added to allow this.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                       = "aksexamplewithprivatednszone1"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  dns_prefix                 = "aksexamplednsprefix1"
  private_cluster_enabled    = true
  private_dns_zone_id        = azurerm_private_dns_zone.example.id
  **use_internal_load_balancer = true**
}
```

### References
(https://docs.microsoft.com/en-us/azure/aks/internal-lb)

**Comment by sebader** [comment]
I assume you are talking about the LB that gets created by default for egress. You can change that:

[outbound_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#outbound_type) - (Optional) The outbound (egress) routing method which should be used for this Kubernetes Cluster. Possible values are loadBalancer, userDefinedRouting, managedNATGateway and userAssignedNATGateway. Defaults to loadBalancer.

**Comment by cpressland** [comment]
Mirroring what @sebader said, we use `userDefinedRouting` and then provision our load balancers something like this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" <-- makes internal lb instead of external
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  loadBalancerIP: 10.10.255.254 <-- added by Flux when Terraform adds a ConfigMap with this value generated from `cidrhost(cluster_subnet, 65534)`, use last IP to make every cluster consistent.
  type: LoadBalancer
```
