### ISSUE TITLE
Upgrading to v3.44.1 breaks authentication in azurerm provider block using github action

### ISSUE THREAD

**Issue by ohbriansung** [hashicorp/terraform-provider-azurerm#20546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

latest

### AzureRM Provider Version

v3.44.1

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    resource_group_name = "service_tfstates"
    container_name      = "tfstate"
    key                 = "key.tfstate"
    use_oidc            = true
    tenant_id           = "XXX"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">3.7.0"
    }
    azuread = {
      source = "hashicorp/azuread"
    }
  }
}

provider "azuread" {
  tenant_id = "XXX"
}

provider "azurerm" {
  tenant_id                  = "XXX"
  subscription_id            = var.deployment_subscription_id
  skip_provider_registration = true
  use_oidc                   = true
  features {}
}
```

### Debug Output/Panic Output

```shell
Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'XXX' was not found in the directory 'Company, Inc.'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 1fe1469a-9841-4a56-a1e3-21cc4124fb00\r\nCorrelation ID: ...\r\nTimestamp: 2023-02-17 17:05:26Z","error_codes":[700016],"timestamp":"2023-02-17 17:05:26Z","trace_id":"...","correlation_id":"...","error_uri":"https://login.microsoftonline.com/error?code=700016"}
```

### Expected Behaviour

Authentication should just work as how we set it up. It was working when using AzureRM v3.43.0.

### Actual Behaviour

The authentication should use "Azure Client ID" but the output suggested that it was actually using "tenant_id". I put "XXX" as you can see, it's the tenant_id we set in terraform file.

### Steps to Reproduce

Github Action Yaml content:

```
name: Deploy Terraform

on:
  workflow_call:
    inputs:
      state_storage_account:
        required: true
        type: string
      environment:
        required: true
        type: string
      target:
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy_terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: "${{ inputs.environment }}.azure"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform -chdir="./terraform/${{ inputs.target }}" init \
            -backend-config="storage_account_name=${{ inputs.state_storage_account }}"

      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform -chdir="./terraform/${{ inputs.target }}" apply \
            -var-file=${{ inputs.environment }}.tfvars --auto-approve -no-color
```

We are providing ARM_CLIENT_ID as an environment variable. The terraform apply failed with the above output.
