### ISSUE TITLE
Terraform incorrectly creates empty state file on azurerm backend

### ISSUE THREAD

**Issue by alicyn** [hashicorp/terraform-provider-azurerm#22518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

backend

### Terraform Configuration Files

```hcl
backend.tf:

terraform {
  backend "azurerm" {
    resource_group_name  = "RG_Name"
    storage_account_name = "storage_account_name"
    container_name       = "tfstate"
    key                  = "aci/storydashboard/terraform.tfstate"
  }
}

Terraform Apply GitHub Actions Workflow:


permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
  pull-requests: write # required for posting comments to issues

name: deploy

on:
  pull_request:
    types: [ labeled ]

jobs:
  deploy-aci:
    name: deploy
    runs-on: ubuntu-latest
    environment: deployments
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
    defaults:
      run:
        working-directory: aci/terraform/azure-container-instances

    steps:
    - name: Checkout aci terraform repo
      uses: actions/checkout@v3
      with:
        repository: myorg/azure-feature-environments
        path: aci
        token: ${{ secrets.ACI_REPOSITORY_ACCESS_TOKEN }}

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -lock=false -out=tf_apply.plan -no-color -input=false

    - name: Terraform Apply
      run: terraform apply -lock=false -input=false "tf_apply.plan" 
```

And the subsequent Terraform Destroy GitHub Actions Workflow

```
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: destroy

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *' #0 is UTC --> 8PM Eastern

jobs:

  destroy:
    runs-on: ubuntu-22.04
    environment: deployments
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
    defaults:
      run:
        working-directory: aci/terraform/azure-container-instances

    steps: 
    - name: Checkout aci terraform repo
      uses: actions/checkout@v3
      with:
        repository: myorg/azure-feature-environments
        path: aci
        token: ${{ secrets.ACI_REPOSITORY_ACCESS_TOKEN }}

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Init
      id: init
      run: terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan Destroy
      id: plan
      run: terraform plan -lock=false -destroy -out=tf_destroy.plan -no-color -input=false

    - name: Terraform Destroy
      run: terraform apply -lock=false "tf_destroy.plan"
```
```


### Debug Output/Panic Output

```shell
Run terraform init -input=false
  terraform init -input=false
  shell: /usr/bin/bash -e {0}
  env:
    ARM_CLIENT_ID: ***
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    ARM_USE_OIDC: true
    TF_VAR_branch_name: storydashboard
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/8f9a3950-8c88-45b3-a781-dfc7cf888c56
/home/runner/work/_temp/8f9a3950-8c88-45b3-a781-dfc7cf888c56/terraform-bin init -input=false

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/azurerm versions matching "3.30.0"...
- Finding hashicorp/azuread versions matching "~> 2.0"...
- Installing hashicorp/azurerm v3.30.0...
- Installed hashicorp/azurerm v3.30.0 (signed by HashiCorp)
- Installing hashicorp/azuread v2.39.0...
- Installed hashicorp/azuread v2.39.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
------
Run terraform plan -lock=false -destroy -out=tf_destroy.plan -no-color -input=false
  terraform plan -lock=false -destroy -out=tf_destroy.plan -no-color -input=false
  shell: /usr/bin/bash -e {0}
  env:
    ARM_CLIENT_ID: ***
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    ARM_USE_OIDC: true
    TF_VAR_branch_name: storydashboard
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/8f9a3950-8c88-45b3-a781-dfc7cf888c56
/home/runner/work/_temp/8f9a3950-8c88-45b3-a781-dfc7cf888c56/terraform-bin plan -lock=false -destroy -out=tf_destroy.plan -no-color -input=false

No changes. No objects need to be destroyed.

Either you have not created any objects yet or the existing objects were
already deleted outside of Terraform.
```

### Expected Behaviour

Upon executing Terraform Plan and Apply, Terraform should write a terraform.tfstate file to the Azure storage blob at the specified path `aci/storydashboard/terraform.tfstate`, and this file contains a long list of objects that are tracking the objects created in Azure (in this case, an application gateway, azure container instance group, log analytics workspace, public ip, etc).

When Terraform Destroy runs after a successful Terraform Apply completed, it should read a valid state file from the remote backend and produce the following plan:

`Plan: 0 to add, 0 to change, 7 to destroy.

Changes to Outputs:
  - appgateway_fqdn                 = "https://ops-example-preview.mydomain.net/" -> null
  - appgateway_public_ip            = "redacted" -> null
  - container_group_ip              = "redacted" -> null
  - current_client_config           = (sensitive value) -> null
  - env_vars                        = (sensitive value) -> null
  - git_branch_name                 = "ops-example-preview" -> null
  - secret_value                    = (sensitive value) -> null
  - storage_access_key_secret_value = (sensitive value) -> null

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: tf_destroy.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "tf_destroy.plan"`

### Actual Behaviour

Terraform writes the following terraform.tfstate file to the Azure storage blob which has an empty resources list: 

`{
  "version": 4,
  "terraform_version": "1.4.6",
  "serial": 6,
  "lineage": "8c2dfd7d-f7ad-dd39-55aa-b125e65f2b7e",
  "outputs": {},
  "resources": [],
  "check_results": null
}
`

Therefore when Terraform Destroy runs on GitHub Actions, it reports that there are no objects, and nothing gets deleted.

### Steps to Reproduce

This issue appears to occur intermittently. See above configuration.

### Important Factoids

Running Terraform in CI Automation
