### ISSUE TITLE
azurerm_container_app - can't update after deploying container via ADO

### ISSUE THREAD

**Issue by jkrilov** [hashicorp/terraform-provider-azurerm#23224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app 

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5.0, < 2.0.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.72.0"
    }
  }
  backend "azurerm" {
  }
}

provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "eastus"
}

resource "azurerm_user_assigned_identity" "test" {
  name                = "mi"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "law"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "test" {
  name                       = "ace"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.test.id

}

resource "azurerm_container_app" "test" {
  name                         = "aca"
  resource_group_name          = azurerm_resource_group.test.name
  container_app_environment_id = azurerm_container_app_environment.test.id
  revision_mode                = "Single"

  ingress {
    external_enabled           = true
    target_port                = 8000
    allow_insecure_connections = false
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }

  template {
    container {
      name   = "test"
      image  = "mcr.microsoft.com/k8se/quickstart:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
    min_replicas = 1
    max_replicas = 1
  }

}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

Error: cannot remove secrets from Container Apps at this time due to a limitation in the Container Apps Service. Please see `https://github.com/microsoft/azure-container-apps/issues/395` for more details

  with azurerm_container_app.test,
  on aca.tf line 65, in resource "azurerm_container_app" "test":
  65: resource "azurerm_container_app" "test" {
```

### Expected Behaviour

The plan should succeed with zero changes following the initial deployment. 

### Actual Behaviour

The `CustomizeDiff()` function is forcing the plan to fail even though there are no secrets applied to the container app.

### Steps to Reproduce

1. Deploy Azure Container App as shown above using Terraform Plan/Apply
2. Update Container App image using **AzureContainerApps@1** task in Azure Pipelines (no secrets applied)
3. Re-run Terraform Plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/22493

**Comment by Joey40** [comment]
@jackofallops just wanted to make sure you saw this issue since you are at least somewhat aware of it from the PR I opened.

**Comment by Joey40** [comment]
This is the pipeline YAML I'm using to update the container image.  Obviously simplified and sanitized.

```
        - task: AzureContainerApps@1
          inputs:
            appSourcePath: $(System.DefaultWorkingDirectory)
            azureSubscription: ${{ variables.service_connection }}
            acrName: $(acr-name)
            acrUsername: $(acr-user)
            acrPassword: $(acr-pass)
            dockerfilePath: dockerfile
            imageToBuild: $(acr-name).azurecr.io/test-container:$(Build.BuildId).$(Build.BuildNumber)
            containerAppName: test-${{ parameters.environment }}-aca
            resourceGroup: test-${{ parameters.environment }}
            containerAppEnvironment: test-${{ parameters.environment }}-ace
            runtimeStack: python:3.11
            targetPort: 8000
            environmentVariables: REDIS_KEY=$(redis-key) REDIS_URL=$(redis-host) REDIS_PORT=$(redis-port) PSQL_FQDN=$(postgresql-fqdn) PSQL_DB=$(postgresql-db) PSQL_USER=$(postgresql-user) PSQL_PASS=$(postgresql-pass)
            disableTelemetry: true
```
