### ISSUE TITLE
Support for azurerm_kubernetes_flux_configuration/git_repository/workload_identity

### ISSUE THREAD

**Issue by amrinder15** [hashicorp/terraform-provider-azurerm#27821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Flux released version 2.4 where they added new feature for **Azure DevOps OIDC Authentication** - https://fluxcd.io/blog/2024/09/flux-v2.4.0/#azure-devops-oidc-authentication
I am using `azurerm_kubernetes_flux_configuration` resource from terraform>azurerm provider to create flux configuration. When i try to add `git_repository` it does not support spec.provider piece as defined in url -> https://fluxcd.io/flux/components/source/gitrepositories/#provider

This will give us an option to use workload identity to pull code from ado repository instead of using PAT token.
It would create below gitrepository yaml:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-repo
  namespace: demo
spec:
  interval: 5m0s
  ref:
    branch: feature/flux-config-repo
  provider: azure
  timeout: 10m0s
  url: https://dev.azure.com/xxx/ado-101/_git/flux_cicd
```

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_flux_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_flux_configuration" "example" {
  name       = "example-fc"
  cluster_id = azurerm_kubernetes_cluster.test.id
  namespace  = "flux"

  git_repository {
    url             = "https://github.com/Azure/arc-k8s-demo"
    reference_type  = "branch"
    reference_value = "main"
    provider        = "azure"
  }

  kustomizations {
    name = "kustomization-1"
  }
}
```
