### ISSUE TITLE
`azurerm_container_app` update fails when ContainerApp probes have unset optional properties

### ISSUE THREAD

**Issue by saarivirtajCGI** [hashicorp/terraform-provider-azurerm#28826]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.19.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
"azurerm_container_app": {
      "app-ca": {
        "//": {
          "metadata": {
            "path": "myapp/app-ca",
            "uniqueId": "app-ca"
          }
        },
        "container_app_environment_id": "...",
        "identity": {
          "identity_ids": [
            "..."
          ],
          "type": "SystemAssigned, UserAssigned"
        },
        "ingress": {
          "allow_insecure_connections": true,
          "external_enabled": true,
          "target_port": 5001,
          "traffic_weight": [
            {
              "latest_revision": true,
              "percentage": 100
            }
          ],
          "transport": "http"
        },
        "lifecycle": {
          "ignore_changes": [
            "secret",
            "dapr",
            "ingress",
            "template",
            "workload_profile_name"
          ]
        },
        "name": "myapp-${var.ENV_NAME}",
        "registry": [
          {
            "identity": "...",
            "server": "..."
          }
        ],
        "resource_group_name": "${azurerm_resource_group.app-rg.name}",
        "revision_mode": "Single",
        "template": {
          "container": [
            {
              "cpu": 0.25,
              "image": "${var.REGISTRY_LOGIN_SERVER}/placeholder:latest",
              "memory": "0.5Gi",
              "name": "placeholder-container"
            }
          ],
          "max_replicas": 1,
          "min_replicas": 0,
          "revision_suffix": "placeholder-revision"
        },
        "workload_profile_name": "Consumption"
      }
    }
```

### Debug Output/Panic Output

```shell
2025-02-19T13:48:17.3440197Z Error: updating Container App (Subscription: "REDACTED"
2025-02-19T13:48:17.3441911Z Resource Group Name: "REDACTED"
2025-02-19T13:48:17.3443801Z Container App Name: "REDACTED"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ContainerAppProbeTimeoutSecondsOutOfRange: Container 'main' 'Type' probe's TimeoutSeconds must be in the range of ['1', '240'].
2025-02-19T13:48:17.3445121Z 
2025-02-19T13:48:17.3445663Z   with azurerm_container_app.app-ca,
2025-02-19T13:48:17.3446574Z   on cdk.tf.json line 240, in resource.azurerm_container_app.app-ca:
2025-02-19T13:48:17.3447405Z  240:       }
2025-02-19T13:48:17.3448136Z 
2025-02-19T13:48:17.3448920Z updating Container App (Subscription: "REDACTED"
2025-02-19T13:48:17.3449634Z Resource Group Name: "REDACTED"
2025-02-19T13:48:17.3451084Z Container App Name: "REDACTED"): performing
2025-02-19T13:48:17.3451658Z CreateOrUpdate: unexpected status 400 (400 Bad Request) with error:
2025-02-19T13:48:17.3452862Z ContainerAppProbeTimeoutSecondsOutOfRange: Container 'main' 'Type' probe's
2025-02-19T13:48:17.3453975Z TimeoutSeconds must be in the range of ['1', '240'].
2025-02-19T13:48:17.4814310Z
```

### Expected Behaviour

So, the Container App has been created ages ago and the app is running fine. Everything regarding the template/revision has been ignored using the `ignore_changes` lifecycle property. 

While performing an update to the resource, the expected behavior is that changes are applied to properties that have changed and are not ignored, and since a working configuration is in place the properties that are ignored should remain as they currently are. Changes should be applied, and since the changes we made are valid, the update should succeed.

However, errors stem from inside properties that are in `ignore_changes` causing the update to fail.

### Actual Behaviour

The error `ContainerAppProbeTimeoutSecondsOutOfRange: Container 'main' 'Type' probe's TimeoutSeconds must be in the range of ['1', '240'].` was encountered and the update operation failed.

I have traced this problem and I do have a workaround already: **the problem is related to how the update process apparently copies the current settings and then performs the resource update request. More specifically, how it handles default/unset values and/or values or properties in `ignore_changes` .** Let me explain in more detail:

The way we deploy Container Apps goes like this:
1) We deploy the Container App itself along with its companion resources, like KeyVaults, Storages etc. Initially we deploy it with a minimal template configuration as above (using a placeholder image). As app revision deployments will be done separately, we ignore `template` and some other properties since we do not want our infra deployments to overwrite any changes made by a separate app revision deployment pipeline.
2) We successfully now deploy app revisions using a separate pipeline. We use AZ CLI command (`az containerapp update -n <appName> -g <appRg> --yaml <pathToConfigFile>`) to create new revisions and the revision configuration is defined in a YAML file. The config file looks like this:
```yaml
configuration:
  secrets: 
  ingress:
    external: true
    allowInsecure: true
    targetPort: 5501
    traffic:
      - latestRevision: true
        weight: 100
    corsPolicy:
      allowCredentials: true
      allowedHeaders: []
      allowedMethods: ['GET']
      allowedOrigins: ['*']
      exposeHeaders: []
      maxAge: 3600
    transport: Http
    customDomains: []
    ipSecurityRestrictions: []
    stickySessions:
      affinity: 'none'
  dapr:
    appId: 'myapp'
    appPort: 5501
    appProtocol: 'http'
    enabled: true
    enableApiLogging: true
template:
  containers:
    - image: 'myapp'
      name: 'main' 
      env:
        - name: ABC
          value: '123'
      resources:
        cpu: 0.5
        memory: 1Gi
      probes:
        - type: liveness
          httpGet:
            path: "/"
            port: 5501
            httpHeaders:
              - name: "x-aca-probe"
                value: "liveness probe"
          initialDelaySeconds: 60
          periodSeconds: 60
      volumeMounts: []
  scale:
    minReplicas: 0
    maxReplicas: 1
  volumes: []
```
3) We make updates to our infra. After having deployed the Container App with Terraform and deploying new Revisions as above, we may need to make changes to our infra including updating the Container App resource. **This is where we are are now.**

The problem manifests itself as we now try to update the Container App resource. **The reason is that in the above configuration we have not defined optional values `failureThreshold`, `successThreshold` and `timeoutSeconds` for the liveness probe**. For some reason when Terraform runs the update, the values that it uses for the forementioned properties in the request are not valid - I don't know exactly the values it tries to use or where it gets them from but as the error message indicates (`TimeoutSeconds must be in the range of ['1', '240']`), it's not what it should be.

When I added `timeoutSeconds` with a valid value to the liveness probe properties and deployed a new revision, Terraform apply then returned the same error but with the _next_ property, `ContainerAppProbeFailureThresholdOutOfRange: Container 'main' 'Type' probe's FailureThreshold must be in the range of ['1', '30']`. After adding all three of the above mentioned properties, the Terraform apply finally succeeded.

**So when probes are defined, all of those properties must be explicitly defined in the probes, or any Terraform updates to the Container App resource will fail.**

I don't know the ins and outs of how Terraform works under the hood but I suspect that when Terraform updates the resource it first performs a GET request to retrieve the current resource definition, then applies changes to that and finally makes a PUT request with the changed content to update the resource. For properties that are under lifecycle ignore I assume it mainly just leaves untouched. I can imagine that the Azure API might be returning something like `null` for the unset property values instead of omitting the entire properties, and as the property values get copied verbatim that then produces an invalid configuration as obviously something like `null` is not a number and the whole house of cards falls down.

**Our current workaround** is to make sure that all those properties are set in our YAML configuration files. If they are not, then any updates to the Container App resource will fail.

### Steps to Reproduce

1) Create a Container App with Terraform, with `template` in lifecycle ignores
2) Deploy a new Revision using AZ CLI `az containerapp update -n <appName> -g <appRg> --yaml <pathToConfigFile>` with a liveness probe as in the example, make sure to **not** set the probe properties `failureThreshold`, `successThreshold` and `timeoutSeconds`
3) Make a change to the Container App Terraform definition (for example, add a Managed Identity)
4) Run terraform apply to apply the change. This should fail with a 400 Bad Request (e.g. `ContainerAppProbeTimeoutSecondsOutOfRange` when `timeoutSeconds` has not been set)

### Important Factoids

We are using CDKTF and produce JSON output, hence the configuration being in JSON
