### ISSUE TITLE
troubles with inconsistent azurerm_kubernetes_cluster.addon_profile.http_application_routing

### ISSUE THREAD

**Issue by pniederlag** [hashicorp/terraform-provider-azurerm#4947]
Running and Updating our aks clusters with the azurerm_kubernetes_cluster resource we often run into a situation where terraform detects a change in addon_profiles.http_application_routing resulting in terraform trying to recreate the cluster.

We have tried different settings over the past and need to take different actions at different times.

We use workspaces, to create clusters for different stages based on the very same terraform-code.

What I could now observe, and might be related:

- We have some clusters in entw that were born on kubernetes version 1.13.x and updated via azure portal to 1.13.12. These Clusters report:

```
export MYKENV=entw; az aks show --resource-group somerg-${MYKENV} --name someaks-${MYKENV} | grep -A10 addon
addonProfiles:
  httpapplicationrouting:
    config: {}
    enabled: false
```
while our fresh kickstarted aks cluster has config: null
```
export MYKENV=entw; az aks show --resource-group somerg-${MYKENV} --name someaks-${MYKENV} | grep -A10 addon
addonProfiles:
  httpapplicationrouting:
    config: null
    enabled: false
```

We are looking for a terraform snippet that we can use consistent across all clusters that ensures:

- addon is not installed (which is azure default)
- cluster is not recreated on consecutive runs

Sry, spotted the issue template to late :-<
