### ISSUE TITLE
azurerm_app_service transient error - "RepoUrl VSTSRM is not supported"

### ISSUE THREAD

**Issue by devedse** [hashicorp/terraform-provider-azurerm#9007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: `0.13.4`

### Affected Resource(s)

azurerm: `version = "=2.30.0"`

### Terraform Configuration Files

```
resource "azurerm_function_app" "azureblobfunction" {
  name                       = "${module.global_variables.applicationName}-azureblobfunction-${var.environment}"
  location                   = azurerm_resource_group.resourcegroup.location
  resource_group_name        = azurerm_resource_group.resourcegroup.name
  app_service_plan_id        = azurerm_app_service_plan.plan.id
  #storage_connection_string = azurerm_storage_account.azureblobfunction_storage.primary_connection_string
  storage_account_name       = azurerm_storage_account.azureblobfunction_storage.name
  storage_account_access_key = azurerm_storage_account.azureblobfunction_storage.primary_access_key
  
  os_type                    = "linux"
  version                    = "~3"

  site_config {
    always_on                = true
    
    ftps_state = "Disabled"
  }

  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME"              = "dotnet"
    "WEBSITE_RUN_FROM_PACKAGE"              = "1"
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE"   = "true"
    "WEBSITE_ENABLE_SYNC_UPDATE_SITE"       = "true"
    "WEBSITE_NODE_DEFAULT_VERSION"          = "10.14.1"
    "APPINSIGHTS_INSTRUMENTATIONKEY"        = ""
    "azuresearch_storage_connectionstring"  = azurerm_storage_account.azuresearch_storage.primary_blob_connection_string
    "ApiKey"                                = var.*******
    "BaseUrl"                               = "https://${azurerm_app_service.*******.default_site_hostname}"
  }

  https_only = true
  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output

```
Error: failed to create App Service Source Control for "*******-azureblobfunction-dev" (Resource Group ""*******-dev"): web.AppsClient#CreateOrUpdateSourceControl: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation not supported: RepoUrl VSTSRM is not supported." Details=[{"Message":"Operation not supported: RepoUrl VSTSRM is not supported."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51024","Message":"Operation not supported: RepoUrl VSTSRM is not supported.","MessageTemplate":"Operation not supported: {0}","Parameters":["RepoUrl VSTSRM is not supported."]}}]

  on azurefunction.tf line 51, in resource "azurerm_function_app" "azureblobfunction":
  51: resource "azurerm_function_app" "azureblobfunction" {
```

### Panic Output

N/A

### Expected Behavior

I would expect the deployment to succeed.

### Actual Behavior

The deployment did not succeed

### Steps to Reproduce

1. `terraform apply`
2. Deploy an Azure blob function with the following Azure DevOps task:
```
        - task: AzureFunctionApp@1
          displayName: 'Azure functions app deploy'
          inputs:
            azureSubscription: '${{ parameters.AZURESUBSCRIPTION }}'
            appType: functionApp
            appName: '${{ parameters.PREFIX }}"*******-azureblobfunction-${{ parameters.ENVIRONMENT }}'
            package: '$(System.ArtifactsDirectory)/dropAzureBlobFunction/blob$(Build.BuildId).zip'
```

### Important Factoids

Deploying to Azure West Europe

### References

The following issue is about the same problem:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/8171

This topic contains a lot more information on this subject.
